export const musicList = ["default", "nothing", "Opening - Bombing Mission", "Bombing Mission",
	"Chasing The Black-Caped Man", "On The Other Side Of The Mountain",
	"Fanfare (intro)", "Mako Reactor", "Fighting", "Fiddle De Chocobo",
	"Anxious Heart", "Still More Fighting", "Cait Sith's Theme", "Aerith's Theme",
	"Final Fantasy VII Main Theme", "Final Fantasy VII Main Theme B", "sato",
	"Rufus' Welcoming Ceremony", "comical", "Who Are You", "Ahead on Our Way",
	"It's Difficult to Stand on Both Feet, Isn't It", "If You Open Your Heart",
	"Waltz de Chocobo", "Don of the Slums", "Trail Of Blood", "Cosmo Canyon",
	"Red XIII's Theme", "Great Warrior", "Lurking in the Darkness",
	"Shinra Company", "Infiltrating Shinra Tower", "Underneath the Rotting Pizza",
	"Farm Boy", "On That Day, Five Years Ago", "Tifa's Theme", "Costa Del Sol",
	"Oppressed People", "Flowers Blooming in the Church", "Crazy Motorcycle",
	"Sandy Badlands", "Those Chosen by the Planet", "Barret's Theme", "Mining Town",
	"Life Stream", "Electric de Chocobo", "Turk's Theme", "Fanfare",
	"Highwind Takes To The Skies", "The Makou Cannon Is Fired ~ Shinra Explodes A",
	"Interrupted By Fireworks", "Those Chosen By The Planet (Intro)", "Cinco de Chocobo",
	"J-E-N-O-V-A", "Descendant Of Shinobi", "Hurry!", "Gold Saucer",
	"Parochial Town", "Good Night, Until Tomorrow", "Continue", "A Great Success",
	"Tango Of Tears", "Racing Chocobo ~ Place Your Bets", "Debut",
	"Off The Edge Of Despair", "Holding My Thoughts In My Heart", "wind",
	"The Nightmare's Beginning", "Honeybee Manor", "Forest Temple",
	"Mark of the Traitor", "Hurry Faster!", "The Great Northern Cave",
	"Cid's Theme", "Sending a Dream Into the Universe", "You Can Hear the Cry of the Planet",
	"Who Am I", "Utai", "Buried in the Snow", "Stolen Materia", "Reunion",
	"Fortress Of The Condor", "One-Winged Angel", "Shinra Army Wages A Full-Scale Attack",
	"Weapon Raid", "Jenova Absolute", "A Secret, Sleeping in the Deep Sea",
	"Judgment Day", "The Birth of God", "sensui", "The Countdown Begins",
	"Steal The Tiny Bronco!", "Those Chosen By The Planet (no intro)",
	"The Makou Cannon Is Fired ~ Shinra Explodes B",
	"The Makou Cannon Is Fired ~ Shinra Explodes C", "Highwind Takes to the Skies",
	"The Prelude", "World Crisis", "heart", "Staff Roll"]